### ISSUE TITLE
Style adjusted, see my remarks

### ISSUE THREAD

**Issue by lborke** [QuantLet/TimeVaryingPenalization#5]
Plz check the commits I have done:
https://github.com/QuantLet/TimeVaryingPenalization/commits/master

Please stick to my style. In particular, every Q has to be in its own subfolder.

In future you should make new Qs according to my example.

This Q has been accepted now and will be put into the D3 visu during the next update procedure.

Thx!

**Comment by zbonakle** [comment]
Dear Lukas, 

Thanks a lot for your contribution. However, I need to change some
smaller details (e.g. the name of the Q doesn't correspond to what the
code does). 

I am going to do it right now, so you can put it into the visualisation.


Best, 

Lenka 

On 16.11.2015 13:27, Lukas Borke wrote: 

> Plz check the commits I have done:
> https://github.com/QuantLet/TimeVaryingPenalization/commits/master [1] 
> 
> Please stick to my style. In particular, every Q has to be in its own subfolder. 
> 
> In future you should make new Qs according to my example. 
> 
> This Q has been accepted now and will be put into the D3 visu during the next update procedure. 
> 
> Thx! 
> 
> --
> Reply to this email directly or view it on GitHub [2].

Lenka Zbonakova
 IRTG 1792-"High Dimensional Non Stationary Time Series"
 Ladislaus von Bortkiewicz Chair of Statistics
 School of Business and Economics
 Humboldt-Universität zu Berlin
 Germany 

Links:
------
[1] https://github.com/QuantLet/TimeVaryingPenalization/commits/master
[2] https://github.com/QuantLet/TimeVaryingPenalization/issues/5

**Comment by lborke** [comment]
Fine.
